/* AUTO-GENERATED by @blomics-platform/design-system — DO NOT EDIT. Source hash: c4ede6b54d5225f47d194c5525e013b998ee8fe304c04daca57f9228d6b50562.
   Edit tokens.json / design.config.json and run `ds build`. */

export declare const PRIMITIVE_RAMPS: readonly ["brand", "gray", "error"];
export declare const PRIMITIVE_STEPS: readonly ["25", "50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
export declare const TEXT_TOKENS: readonly ["text-white", "text-primary"];
export declare const BG_TOKENS: readonly ["bg-primary", "bg-brand-solid", "bg-brand-solid_hover"];
export declare const BORDER_TOKENS: readonly ["border-error"];
export declare const FG_TOKENS: readonly ["fg-primary"];
export declare const UTILITY_TOKENS: readonly ["utility-gray-50"];
export declare const ALPHA_TOKENS: readonly ["alpha-black-50"];

export type PrimitiveRamp = (typeof PRIMITIVE_RAMPS)[number];
export type PrimitiveStep = (typeof PRIMITIVE_STEPS)[number];
export type TextToken = (typeof TEXT_TOKENS)[number];
export type BgToken = (typeof BG_TOKENS)[number];
export type BorderToken = (typeof BORDER_TOKENS)[number];
export type FgToken = (typeof FG_TOKENS)[number];
export type UtilityToken = (typeof UTILITY_TOKENS)[number];
export type AlphaToken = (typeof ALPHA_TOKENS)[number];
