/* AUTO-GENERATED by @blomics-platform/design-system — DO NOT EDIT. Source hash: c4ede6b54d5225f47d194c5525e013b998ee8fe304c04daca57f9228d6b50562.
   Edit tokens.json / design.config.json and run `ds build`. */

export const PRIMITIVE_RAMPS = ["brand", "gray", "error"] as const;
export const PRIMITIVE_STEPS = ["25", "50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"] as const;
export const TEXT_TOKENS = ["text-white", "text-primary"] as const;
export const BG_TOKENS = ["bg-primary", "bg-brand-solid", "bg-brand-solid_hover"] as const;
export const BORDER_TOKENS = ["border-error"] as const;
export const FG_TOKENS = ["fg-primary"] as const;
export const UTILITY_TOKENS = ["utility-gray-50"] as const;
export const ALPHA_TOKENS = ["alpha-black-50"] as const;

export type PrimitiveRamp = (typeof PRIMITIVE_RAMPS)[number];
export type PrimitiveStep = (typeof PRIMITIVE_STEPS)[number];
export type TextToken = (typeof TEXT_TOKENS)[number];
export type BgToken = (typeof BG_TOKENS)[number];
export type BorderToken = (typeof BORDER_TOKENS)[number];
export type FgToken = (typeof FG_TOKENS)[number];
export type UtilityToken = (typeof UTILITY_TOKENS)[number];
export type AlphaToken = (typeof ALPHA_TOKENS)[number];
