const HEADER = (h) => `/* AUTO-GENERATED by @blomics-platform/design-system — DO NOT EDIT. Source hash: ${h}.\n   Edit tokens.json / design.config.json and run \`ds build\`. */`;
const PRIMITIVE_STEPS = ["25", "50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const q = (s) => JSON.stringify(s);
const arr = (names) => "[" + names.map(q).join(", ") + "]";

function partition(baseKeys) {
  const g = { text: [], bg: [], border: [], fg: [], utility: [], alpha: [] };
  for (const k of baseKeys) {
    if (k === "white" || k === "black") continue; // 앵커는 역할 리스트 제외
    if (k.startsWith("text-")) g.text.push(k);
    else if (k.startsWith("bg-")) g.bg.push(k);
    else if (k.startsWith("border-")) g.border.push(k);
    else if (k.startsWith("fg-")) g.fg.push(k);
    else if (k.startsWith("utility-")) g.utility.push(k);
    else if (k.startsWith("alpha-")) g.alpha.push(k);
  }
  return g;
}

export function renderTokens(tokens, config, sourceHash) {
  const ramps = Object.keys(tokens.scales);
  const g = partition(Object.keys(tokens.base)); // text-white는 text-로 시작 → TEXT_TOKENS 포함
  const LISTS = [
    ["PRIMITIVE_RAMPS", ramps, "PrimitiveRamp"], ["PRIMITIVE_STEPS", PRIMITIVE_STEPS, "PrimitiveStep"],
    ["TEXT_TOKENS", g.text, "TextToken"], ["BG_TOKENS", g.bg, "BgToken"], ["BORDER_TOKENS", g.border, "BorderToken"],
    ["FG_TOKENS", g.fg, "FgToken"], ["UTILITY_TOKENS", g.utility, "UtilityToken"], ["ALPHA_TOKENS", g.alpha, "AlphaToken"],
  ];
  const tsLines = [HEADER(sourceHash), ""];
  for (const [name, names] of LISTS) tsLines.push(`export const ${name} = ${arr(names)} as const;`);
  tsLines.push("");
  for (const [name, , alias] of LISTS) tsLines.push(`export type ${alias} = (typeof ${name})[number];`);
  const dtsLines = [HEADER(sourceHash), ""];
  for (const [name, names] of LISTS) dtsLines.push(`export declare const ${name}: readonly ${arr(names)};`);
  dtsLines.push("");
  for (const [name, , alias] of LISTS) dtsLines.push(`export type ${alias} = (typeof ${name})[number];`);
  return { ts: tsLines.join("\n") + "\n", dts: dtsLines.join("\n") + "\n" };
}
