// v0.2.0 Untitled UI 방출. 분류는 프리픽스 우선(utility-brand-600 오분류 방지).
const ROLE_PREFIXES = ["text-", "bg-", "border-", "fg-"];
const UTIL_PREFIXES = ["utility-", "alpha-"];
const ROLE_PROP = { "text-": "color", "bg-": "background-color", "border-": "border-color", "fg-": "color" };
const UTILITY_SKIP = new Set(["text-white"]); // --color-white가 이미 text-white 유틸 생성

function customVariantLine(config) { const s = config.darkSelector; return `@custom-variant ${config.darkVariantName} (&:where(${s}, ${s} *));`; }
function header(h) { return `/* AUTO-GENERATED by @blomics-platform/design-system — DO NOT EDIT. Source hash: ${h}.\n   Edit tokens.json / design.config.json and run \`ds build\`.\n   NOTE: 소비자 globals.css가 \`@import "tailwindcss";\` 를 이 파일 import 위에 두어야 한다. */`; }

const hasPrefix = (k, ps) => ps.some((p) => k.startsWith(p));
const isRole = (k) => hasPrefix(k, ROLE_PREFIXES);
const isUtil = (k) => hasPrefix(k, UTIL_PREFIXES);
const isPrimitive = (k) => !isRole(k) && !isUtil(k) && (/-\d{2,3}$/.test(k) || k === "white" || k === "black");

function primitiveOrder(keys) {
  const rampOrder = new Map(); let idx = 0;
  const parsed = keys.map((k) => { const m = k.match(/^(.+)-(\d{2,3})$/); if (m) { if (!rampOrder.has(m[1])) rampOrder.set(m[1], idx++); return { k, ramp: m[1], step: Number(m[2]) }; } if (!rampOrder.has(k)) rampOrder.set(k, idx++); return { k, ramp: k, step: -1 }; });
  return parsed.sort((a, b) => (rampOrder.get(a.ramp) - rampOrder.get(b.ramp)) || (a.step - b.step)).map((p) => p.k);
}
const declLines = (keys, map) => keys.map((k) => "  --color-" + k + ": " + map[k] + ";");

function utilRule(className, prop, varKey) { return `@utility ${className} { ${prop}: var(--color-${varKey}); }`; }
// Tailwind 의 divide-y/divide-x 는 자식(:not(:last-child))에 보더 '폭'만 준다. 색은 divide-<color>
// 유틸 몫인데 역할 토큰에는 그게 없어 currentColor 로 폴백한다(다크 배경에 흰 줄). 그래서
// border-<role> 마다 짝이 되는 divide-<role> 을 내되, 컨테이너가 아니라 자식을 칠한다.
function divideRule(role, varKey) { return `@utility divide-${role} { & > :not(:last-child) { border-color: var(--color-${varKey}); } }`; }
function emitUtilities(roleUtilKeys) {
  const out = [];
  for (const k of roleUtilKeys) {
    if (UTILITY_SKIP.has(k)) continue;
    // utility-*/alpha-* 는 역할이 아니라 팔레트라 어느 속성에 쓸지 정해져 있지 않다 → 세 속성 모두 발행.
    // border- 는 tint 배경 + 동계열 보더(배지 등) 조합 때문에 필요하다.
    if (k.startsWith("utility-") || k.startsWith("alpha-")) { out.push(utilRule("bg-" + k, "background-color", k)); out.push(utilRule("text-" + k, "color", k)); out.push(utilRule("border-" + k, "border-color", k)); continue; }
    const prefix = ROLE_PREFIXES.find((p) => k.startsWith(p));
    out.push(utilRule(k, ROLE_PROP[prefix], k));
    if (prefix === "border-") out.push(divideRule(k.slice("border-".length), k));
  }
  return out;
}

export function renderCss(resolvedLight, resolvedDark, config, sourceHash) {
  const keys = Object.keys(resolvedLight);
  const primKeys = keys.filter(isPrimitive);
  const roleUtilKeys = keys.filter((k) => isRole(k) || isUtil(k));
  const lines = [header(sourceHash), "", customVariantLine(config), ""];
  // (2) @theme 프리미티브만
  const primOrdered = primitiveOrder(primKeys);
  lines.push("@theme {"); lines.push(...declLines(primOrdered, resolvedLight)); lines.push("}", "");
  // (3) 프리미티브 [dark] delta
  const primDark = primOrdered.filter((k) => resolvedDark[k] !== resolvedLight[k]);
  lines.push(config.darkSelector + " {"); lines.push(...declLines(primDark, resolvedDark)); lines.push("}", "");
  // (4) :root 역할/유틸/alpha (삽입순, text-white var 포함)
  lines.push(":root {"); lines.push(...declLines(roleUtilKeys, resolvedLight)); lines.push("}", "");
  // (5) 역할/유틸/alpha [dark] delta
  const roleDark = roleUtilKeys.filter((k) => resolvedDark[k] !== resolvedLight[k]);
  lines.push(config.darkSelector + " {"); lines.push(...declLines(roleDark, resolvedDark)); lines.push("}", "");
  // (6) @utility 패스
  lines.push(...emitUtilities(roleUtilKeys));
  return lines.join("\n");
}
